# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:   
  build:    
    runs-on: ubuntu-latest   
    env:      
      DOCKER_REGISTRY: xyphedocker      
      DOCKER_IMAGE: home_power:smartmeter_influx_v0001      
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      DOCKER_TARGET_PLATFORM: linux/arm/v7                 
    steps:    
    - name: Checkout the code       
      uses: actions/checkout@v1          
    - name: Set up Docker Buildx      
      uses: docker/setup-buildx-action@v3   
      with:        
        version: latest    
    - name: Prepare      
      if: success()      
      id: prepare      
      run: |        
        echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}        
        echo ::set-output name=docker_image::${DOCKER_REGISTRY}/${DOCKER_IMAGE}        
        echo ::set-output name=version::${GITHUB_RUN_NUMBER}      
    - name: Login to Docker Hub
      if: success() 
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}       
    - name: Run Buildx (push image)      
      if: success()      
      run: |        
        docker buildx build \        
        --platform ${{ steps.prepare.outputs.docker_platform }} \        
        --tag ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }} \        
        --file ./Dockerfile \  
        --context: ./ \
        --output type=image,push=false .
